import { label } from '../constants/colours'
import { MaplibreLayerDefinition } from '../types/maplibre'
import {
  all,
  greaterThan,
  greaterThanOrEqual,
  has,
  inValues,
  kindEquals,
  lessThan,
  lessThanOrEqual,
} from '../utils/filters'
import { stops } from '../utils/style'

export default function labelLayer(): MaplibreLayerDefinition[] {
  return [
    {
      id: 'label-address-housenumber',
      type: 'symbol',
      'source-layer': 'addresses',
      minzoom: 17,
      filter: has('housenumber'),
      layout: {
        'text-field': '{housenumber}',
        'text-font': ['noto_sans_regular'],
        'symbol-placement': 'point',
        'text-anchor': 'center',
        'text-size': stops([
          [17, 8],
          [19, 10],
        ]),
      },
      paint: {
        'text-halo-color': label.addressNumberHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
        'icon-color': label.addressNumberText,
        'text-color': label.addressNumberText,
      },
    },
    {
      id: 'label-motorway-shield',
      type: 'symbol',
      'source-layer': 'street_labels',
      minzoom: 14,
      filter: kindEquals('motorway'),
      layout: {
        'text-field': '{ref}',
        'text-font': ['noto_sans_bold'],
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-size': stops([
          [14, 10],
          [18, 12],
          [20, 16],
        ]),
        'text-rotation-alignment': 'viewport',
      },
      paint: {
        'icon-color': label.motorwayShieldText,
        'text-color': label.motorwayShieldText,
        'text-halo-color': label.motorwayShieldHalo,
        'text-halo-width': 0.1,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-street-pedestrian',
      type: 'symbol',
      'source-layer': 'street_labels',
      minzoom: 12,
      filter: kindEquals('pedestrian'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-size': stops([
          [12, 10],
          [15, 13],
        ]),
      },
      paint: {
        'icon-color': label.streetText,
        'text-color': label.streetText,
        'text-halo-color': label.streetHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-street-livingstreet',
      type: 'symbol',
      'source-layer': 'street_labels',
      minzoom: 12,
      filter: kindEquals('living_street'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-size': stops([
          [12, 10],
          [15, 13],
        ]),
      },
      paint: {
        'icon-color': label.streetText,
        'text-color': label.streetText,
        'text-halo-color': label.streetHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-street-residential',
      type: 'symbol',
      'source-layer': 'street_labels',
      minzoom: 12,
      filter: kindEquals('residential'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-size': stops([
          [12, 10],
          [15, 13],
        ]),
      },
      paint: {
        'icon-color': label.streetText,
        'text-color': label.streetText,
        'text-halo-color': label.streetHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-street-unclassified',
      type: 'symbol',
      'source-layer': 'street_labels',
      minzoom: 12,
      filter: kindEquals('unclassified'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-size': stops([
          [12, 10],
          [15, 13],
        ]),
      },
      paint: {
        'icon-color': label.streetText,
        'text-color': label.streetText,
        'text-halo-color': label.streetHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-street-tertiary',
      type: 'symbol',
      'source-layer': 'street_labels',
      minzoom: 12,
      filter: kindEquals('tertiary'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-size': stops([
          [12, 10],
          [15, 13],
        ]),
      },
      paint: {
        'icon-color': label.streetText,
        'text-color': label.streetText,
        'text-halo-color': label.streetHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-street-secondary',
      type: 'symbol',
      'source-layer': 'street_labels',
      minzoom: 12,
      filter: kindEquals('secondary'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-size': stops([
          [12, 10],
          [15, 13],
        ]),
      },
      paint: {
        'icon-color': label.streetText,
        'text-color': label.streetText,
        'text-halo-color': label.streetHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-street-primary',
      type: 'symbol',
      'source-layer': 'street_labels',
      minzoom: 12,
      filter: kindEquals('primary'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-size': stops([
          [12, 10],
          [15, 13],
        ]),
      },
      paint: {
        'icon-color': label.streetText,
        'text-color': label.streetText,
        'text-halo-color': label.streetHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-street-trunk',
      type: 'symbol',
      'source-layer': 'street_labels',
      minzoom: 12,
      filter: kindEquals('trunk'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-size': stops([
          [12, 10],
          [15, 13],
        ]),
      },
      paint: {
        'icon-color': label.streetText,
        'text-color': label.streetText,
        'text-halo-color': label.streetHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-place-neighbourhood',
      type: 'symbol',
      'source-layer': 'place_labels',
      minzoom: 14,
      filter: kindEquals('neighbourhood'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-size': stops([[14, 12]]),
        'text-transform': 'uppercase',
      },
      paint: {
        'icon-color': label.placeNeighbourhoodText,
        'text-color': label.placeNeighbourhoodText,
        'text-halo-color': label.placeHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-place-quarter',
      type: 'symbol',
      'source-layer': 'place_labels',
      minzoom: 13,
      filter: kindEquals('quarter'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-size': stops([[13, 13]]),
        'text-transform': 'uppercase',
      },
      paint: {
        'icon-color': label.placeQuarterText,
        'text-color': label.placeQuarterText,
        'text-halo-color': label.placeHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-place-suburb',
      type: 'symbol',
      'source-layer': 'place_labels',
      minzoom: 11,
      filter: kindEquals('suburb'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-size': stops([
          [11, 11],
          [13, 14],
        ]),
        'text-transform': 'uppercase',
      },
      paint: {
        'icon-color': label.placeSuburbText,
        'text-color': label.placeSuburbText,
        'text-halo-color': label.placeHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-place-hamlet',
      type: 'symbol',
      'source-layer': 'place_labels',
      minzoom: 13,
      filter: kindEquals('hamlet'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-size': stops([
          [10, 11],
          [12, 14],
        ]),
      },
      paint: {
        'icon-color': label.placeHamletVillageTownText,
        'text-color': label.placeHamletVillageTownText,
        'text-halo-color': label.placeHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-place-village',
      type: 'symbol',
      'source-layer': 'place_labels',
      minzoom: 11,
      filter: kindEquals('village'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-size': stops([
          [9, 11],
          [12, 14],
        ]),
      },
      paint: {
        'icon-color': label.placeHamletVillageTownText,
        'text-color': label.placeHamletVillageTownText,
        'text-halo-color': label.placeHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-place-town',
      type: 'symbol',
      'source-layer': 'place_labels',
      minzoom: 9,
      filter: kindEquals('town'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-size': stops([
          [8, 11],
          [12, 14],
        ]),
      },
      paint: {
        'icon-color': label.placeHamletVillageTownText,
        'text-color': label.placeHamletVillageTownText,
        'text-halo-color': label.placeHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-boundary-state',
      type: 'symbol',
      'source-layer': 'boundary_labels',
      minzoom: 5,
      filter: inValues('admin_level', 4, '4'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-transform': 'uppercase',
        'text-anchor': 'top',
        'text-offset': [0, 0.2],
        'text-padding': 0,
        'text-optional': true,
        'text-size': stops([
          [5, 8],
          [8, 12],
        ]),
      },
      paint: {
        'icon-color': label.boundaryStateText,
        'text-color': label.boundaryStateText,
        'text-halo-color': label.boundaryStateHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-place-city',
      type: 'symbol',
      'source-layer': 'place_labels',
      minzoom: 7,
      filter: kindEquals('city'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-size': stops([
          [7, 11],
          [10, 14],
        ]),
      },
      paint: {
        'icon-color': label.placeCityText,
        'text-color': label.placeCityText,
        'text-halo-color': label.placeHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-place-statecapital',
      type: 'symbol',
      'source-layer': 'place_labels',
      minzoom: 6,
      filter: kindEquals('state_capital'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-size': stops([
          [6, 11],
          [10, 15],
        ]),
      },
      paint: {
        'icon-color': label.placeCityText,
        'text-color': label.placeCityText,
        'text-halo-color': label.placeHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-place-capital',
      type: 'symbol',
      'source-layer': 'place_labels',
      minzoom: 5,
      filter: kindEquals('capital'),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-size': stops([
          [5, 12],
          [10, 16],
        ]),
      },
      paint: {
        'icon-color': label.placeCityText,
        'text-color': label.placeCityText,
        'text-halo-color': label.placeHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-boundary-country-small',
      type: 'symbol',
      'source-layer': 'boundary_labels',
      minzoom: 4,
      filter: all(
        inValues('admin_level', 2, '2'),
        lessThanOrEqual('way_area', 10000000),
      ),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-transform': 'uppercase',
        'text-anchor': 'top',
        'text-offset': [0, 0.2],
        'text-padding': 0,
        'text-optional': true,
        'text-size': stops([
          [4, 8],
          [5, 11],
        ]),
      },
      paint: {
        'icon-color': label.boundaryCountryText,
        'text-color': label.boundaryCountryText,
        'text-halo-color': label.boundaryCountryHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-boundary-country-medium',
      type: 'symbol',
      'source-layer': 'boundary_labels',
      minzoom: 3,
      filter: all(
        inValues('admin_level', 2, '2'),
        lessThan('way_area', 90000000),
        greaterThan('way_area', 10000000),
      ),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-transform': 'uppercase',
        'text-anchor': 'top',
        'text-offset': [0, 0.2],
        'text-padding': 0,
        'text-optional': true,
        'text-size': stops([
          [3, 8],
          [5, 12],
        ]),
      },
      paint: {
        'icon-color': label.boundaryCountryText,
        'text-color': label.boundaryCountryText,
        'text-halo-color': label.boundaryCountryHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'label-boundary-country-large',
      type: 'symbol',
      'source-layer': 'boundary_labels',
      minzoom: 2,
      filter: all(
        inValues('admin_level', 2, '2'),
        greaterThanOrEqual('way_area', 90000000),
      ),
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['noto_sans_regular'],
        'text-transform': 'uppercase',
        'text-anchor': 'top',
        'text-offset': [0, 0.2],
        'text-padding': 0,
        'text-optional': true,
        'text-size': stops([
          [2, 8],
          [5, 13],
        ]),
      },
      paint: {
        'icon-color': label.boundaryCountryText,
        'text-color': label.boundaryCountryText,
        'text-halo-color': label.boundaryCountryHalo,
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
  ]
}
