import { MaplibreLayerDefinition } from '../types/maplibre'
import { all, equals, kindIn, linkRoad, notEquals } from '../utils/filters'
import { stops } from '../utils/style'

export default function roadOutlineLayer(): MaplibreLayerDefinition[] {
  return [
    {
      id: 'street-track:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        equals('kind', 'track'),
        notEquals('bridge', true),
        notEquals('tunnel', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgba(248, 242, 218, 1)',
        'line-width': stops([
          [14, 2],
          [16, 4],
          [18, 18],
          [19, 48],
          [20, 96],
        ]),
        'line-opacity': stops([
          [14, 0],
          [15, 0.5],
        ]),
      },
    },
    {
      id: 'street-pedestrian:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        equals('kind', 'pedestrian'),
        notEquals('bridge', true),
        notEquals('tunnel', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgba(175, 175, 191, 1)',
        'line-width': stops([
          [12, 2],
          [14, 3],
          [16, 6],
          [18, 26],
          [19, 42],
          [20, 102],
        ]),
        'line-opacity': stops([
          [12, 0],
          [13, 1],
        ]),
      },
    },
    {
      id: 'street-service:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        equals('kind', 'service'),
        notEquals('bridge', true),
        notEquals('tunnel', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(221,220,218)',
        'line-width': stops([
          [14, 1],
          [16, 3],
          [18, 12],
          [19, 30],
          [20, 48],
        ]),
        'line-opacity': stops([
          [15, 0],
          [16, 1],
        ]),
      },
    },
    {
      id: 'street-livingstreet:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        equals('kind', 'living_street'),
        notEquals('bridge', true),
        notEquals('tunnel', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(207,205,202)',
        'line-width': stops([
          [12, 2],
          [14, 3],
          [16, 6],
          [18, 26],
          [19, 64],
          [20, 128],
        ]),
        'line-opacity': stops([
          [12, 0],
          [13, 1],
        ]),
      },
    },
    {
      id: 'street-residential:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        equals('kind', 'residential'),
        notEquals('bridge', true),
        notEquals('tunnel', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(207,205,202)',
        'line-width': stops([
          [12, 2],
          [14, 3],
          [16, 6],
          [18, 26],
          [19, 42],
          [20, 102],
        ]),
        'line-opacity': stops([
          [12.5, 0],
          [13, 1],
        ]),
      },
    },
    {
      id: 'street-unclassified:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        equals('kind', 'unclassified'),
        notEquals('bridge', true),
        notEquals('tunnel', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(207,205,202)',
        'line-width': stops([
          [12, 2],
          [14, 3],
          [16, 6],
          [18, 26],
          [19, 42],
          [20, 102],
        ]),
        'line-opacity': stops([
          [12.5, 0],
          [13, 1],
        ]),
      },
    },
    {
      id: 'street-busway:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        equals('kind', 'busway'),
        notEquals('bridge', true),
        notEquals('tunnel', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgba(229, 96, 96, 1)',
        'line-width': stops([
          [12, 2],
          [14, 3],
          [16, 6],
          [18, 26],
          [19, 42],
          [20, 102],
        ]),
        'line-opacity': stops([
          [12.5, 0],
          [13, 1],
        ]),
      },
    },
    {
      id: 'street-tertiary-link:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        notEquals('bridge', true),
        notEquals('tunnel', true),
        kindIn('tertiary'),
        linkRoad(),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(207,205,202)',
        'line-width': stops([
          [12, 2],
          [14, 3],
          [16, 6],
          [18, 26],
          [19, 64],
          [20, 128],
        ]),
        'line-opacity': stops([
          [12, 0],
          [13, 1],
        ]),
      },
    },
    {
      id: 'street-secondary-link:outline',
      type: 'line',
      'source-layer': 'streets',
      minzoom: 13,
      filter: all(
        notEquals('bridge', true),
        notEquals('tunnel', true),
        kindIn('secondary'),
        linkRoad(),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(233,172,119)',
        'line-width': stops([
          [12, 2],
          [14, 3],
          [16, 7],
          [18, 14],
          [20, 40],
        ]),
        'line-opacity': [
          'case',
          ['get', 'construction'],
          ['literal', 0.5],
          ['literal', 1],
        ],
      },
    },
    {
      id: 'street-primary-link:outline',
      type: 'line',
      'source-layer': 'streets',
      minzoom: 13,
      filter: all(
        notEquals('bridge', true),
        notEquals('tunnel', true),
        kindIn('primary'),
        linkRoad(),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(233,172,119)',
        'line-width': stops([
          [12, 2],
          [14, 3],
          [16, 7],
          [18, 14],
          [20, 40],
        ]),
        'line-opacity': [
          'case',
          ['get', 'construction'],
          ['literal', 0.5],
          ['literal', 1],
        ],
      },
    },
    {
      id: 'street-trunk-link:outline',
      type: 'line',
      'source-layer': 'streets',
      minzoom: 13,
      filter: all(
        notEquals('bridge', true),
        notEquals('tunnel', true),
        kindIn('trunk'),
        linkRoad(),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(233,172,119)',
        'line-width': stops([
          [12, 2],
          [14, 3],
          [16, 7],
          [18, 14],
          [20, 40],
        ]),
        'line-opacity': [
          'case',
          ['get', 'construction'],
          ['literal', 0.5],
          ['literal', 1],
        ],
      },
    },
    {
      id: 'street-motorway-link:outline',
      type: 'line',
      'source-layer': 'streets',
      minzoom: 11,
      filter: all(
        notEquals('bridge', true),
        notEquals('tunnel', true),
        kindIn('motorway'),
        linkRoad(),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgba(233, 119, 119, 1)',
        'line-width': stops([
          [12, 2],
          [14, 3],
          [16, 7],
          [18, 14],
          [20, 40],
        ]),
        'line-opacity': [
          'case',
          ['get', 'construction'],
          ['literal', 0.5],
          ['literal', 1],
        ],
      },
    },
    {
      id: 'street-tertiary:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        notEquals('bridge', true),
        notEquals('tunnel', true),
        kindIn('tertiary'),
        notEquals('link', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(207,205,202)',
        'line-width': stops([
          [12, 4],
          [14, 5],
          [16, 9],
          [18, 34],
          [19, 64],
          [20, 128],
        ]),
        'line-opacity': stops([
          [12, 0],
          [13, 1],
        ]),
      },
    },
    {
      id: 'street-secondary:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        notEquals('bridge', true),
        notEquals('tunnel', true),
        kindIn('secondary'),
        notEquals('link', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(233,172,119)',
        'line-width': stops([
          [11, 2],
          [14, 5],
          [16, 12],
          [18, 30],
          [19, 58],
          [20, 122],
        ]),
        'line-opacity': stops([
          [11, 0],
          [12, 1],
        ]),
      },
    },
    {
      id: 'street-primary:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        notEquals('bridge', true),
        notEquals('tunnel', true),
        kindIn('primary'),
        notEquals('link', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgb(233,172,119)',
        'line-width': stops([
          [8, 0],
          [9, 1],
          [10, 4],
          [14, 6],
          [16, 12],
          [18, 30],
          [19, 58],
          [20, 122],
        ]),
        'line-opacity': [
          'case',
          ['get', 'construction'],
          ['literal', 0.5],
          ['literal', 1],
        ],
      },
    },
    {
      id: 'street-trunk:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        notEquals('bridge', true),
        notEquals('tunnel', true),
        kindIn('trunk'),
        notEquals('link', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgba(249, 172, 104, 1)',
        'line-width': stops([
          [7, 0],
          [8, 2],
          [10, 4],
          [14, 6],
          [16, 12],
          [18, 30],
          [19, 58],
          [20, 122],
        ]),
        'line-opacity': [
          'case',
          ['get', 'construction'],
          ['literal', 0.5],
          ['literal', 1],
        ],
      },
    },
    {
      id: 'street-motorway:outline',
      type: 'line',
      'source-layer': 'streets',
      filter: all(
        notEquals('bridge', true),
        notEquals('tunnel', true),
        kindIn('motorway'),
        notEquals('link', true),
      ),
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'rgba(233, 119, 119, 1)',
        'line-width': stops([
          [5, 0],
          [6, 2],
          [10, 5],
          [14, 5],
          [16, 14],
          [18, 38],
          [19, 84],
          [20, 168],
        ]),
        'line-opacity': [
          'case',
          ['get', 'construction'],
          ['literal', 0.5],
          ['literal', 1],
        ],
      },
    },
  ]
}
