import { MaplibreLayerDefinition } from '../types/maplibre'
import {
  all,
  equals,
  inValues,
  kindEquals,
  kindIn,
  notInValues,
} from '../utils/filters'
import { stops } from '../utils/style'

export default function symbolLayer(): MaplibreLayerDefinition[] {
  return [
    {
      id: 'symbol-transit-ferry',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 16,
      filter: all(kindEquals('ferry_terminal')),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [16, 0.5],
          [18, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
      },
      paint: {
        'icon-opacity': 0.7,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-ferry-official',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 16,
      filter: all(
        kindEquals('ferry_terminal'),
        inValues('network', 'Sydney Ferries'),
      ),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [16, 0.5],
          [18, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'transport:tfnsw\\ferry',
      },
      paint: {
        'icon-opacity': 1,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-bus',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 16,
      filter: kindEquals('bus_stop'),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [16, 0.5],
          [18, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'basics:icon-bus',
      },
      paint: {
        'icon-opacity': 0.7,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-bus-official',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 16,
      filter: all(
        kindEquals('bus_stop'),
        inValues(
          'network',
          'Transport Buses',
          'Skybus',
          'PTV - Metropolitan Buses',
        ),
      ),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [16, 0.5],
          [18, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': [
          'match',
          ['get', 'network'],
          'Transport Buses',
          'transport:tfnsw\\bus',
          'PTV - Metropolitan Buses',
          'transport:ptv\\bus',
          'Skybus',
          'transport:ptv\\skybus',
          '',
        ],
      },
      paint: {
        'icon-opacity': 1,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-tram',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 15,
      filter: kindEquals('tram_stop'),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [15, 0.5],
          [17, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'basics:transport-tram',
      },
      paint: {
        'icon-opacity': 0.7,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-tram-official',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 15,
      filter: all(
        kindEquals('tram_stop'),
        inValues('network', 'PTV - Metropolitan Trams'),
      ),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [15, 0.5],
          [17, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'transport:ptv\\tram',
      },
      paint: {
        'icon-opacity': 1,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-subway',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 14,
      filter: all(kindIn('station', 'halt'), equals('station', 'subway')),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [14, 0.5],
          [16, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'basics:icon-rail_metro',
      },
      paint: {
        'icon-opacity': 0.7,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-subway-official',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 13,
      filter: all(
        kindIn('station', 'halt'),
        equals('station', 'subway'),
        inValues('network', 'Sydney Metro'),
      ),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [13, 0.5],
          [15, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'transport:tfnsw\\metro',
      },
      paint: {
        'icon-opacity': 1,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-lightrail',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 14,
      filter: all(kindIn('station', 'halt'), equals('station', 'light_rail')),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [14, 0.5],
          [16, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'basics:icon-rail_light',
      },
      paint: {
        'icon-opacity': 0.7,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-lightrail-official',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 14,
      filter: all(
        kindIn('station', 'halt'),
        equals('station', 'light_rail'),
        equals('network', 'Sydney Light Rail'),
      ),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [14, 0.5],
          [16, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'transport:tfnsw\\tram',
      },
      paint: {
        'icon-opacity': 1,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-station',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 13,
      filter: all(
        kindIn('station', 'halt'),
        notInValues('station', 'light_rail', 'subway'),
      ),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [13, 0.5],
          [15, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'basics:icon-rail',
      },
      paint: {
        'icon-opacity': 0.7,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-station-official',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 13,
      filter: all(
        kindIn('station', 'halt'),
        notInValues('station', 'light_rail', 'subway'),
        inValues(
          'network',
          'Sydney Trains',
          'NSW TrainLink',
          'PTV - Metropolitan Trains',
          'PTV - Regional Trains',
        ),
      ),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [13, 0.5],
          [15, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': [
          'match',
          ['get', 'network'],
          'Sydney Trains',
          'transport:tfnsw\\train',
          'NSW TrainLink',
          'transport:tfnsw\\train',
          'PTV - Metropolitan Trains',
          'transport:ptv\\train',
          'PTV - Regional Trains',
          'transport:ptv\\train_regional',
          '',
        ],
      },
      paint: {
        'icon-opacity': 1,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-airfield',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 13,
      filter: all(kindEquals('aerodrome'), ['!has', 'iata']),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [13, 0.5],
          [15, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'basics:icon-airfield',
      },
      paint: {
        'icon-opacity': 0.7,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
    {
      id: 'symbol-transit-airport',
      type: 'symbol',
      'source-layer': 'public_transport',
      minzoom: 12,
      filter: all(kindEquals('aerodrome'), ['has', 'iata']),
      layout: {
        'text-field': ['get', 'name'],
        'icon-size': stops([
          [12, 0.5],
          [14, 1],
        ]),
        'symbol-placement': 'point',
        'icon-keep-upright': true,
        'text-font': ['noto_sans_regular'],
        'text-size': 10,
        'icon-anchor': 'bottom',
        'text-anchor': 'top',
        'icon-image': 'basics:icon-airport',
      },
      paint: {
        'icon-opacity': 0.7,
        'icon-color': 'rgb(102,98,106)',
        'text-color': 'rgb(102,98,106)',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
        'text-halo-blur': 1,
      },
    },
  ]
}
